version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
