# Используем официальный образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем только package.json и package-lock.json для кеширования слоев
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Устанавливаем Nest CLI глобально (опционально, если нужно)
RUN npm install -g @nestjs/cli

# Копируем весь проект
COPY . .

# Указываем порт для приложения
EXPOSE 3000

# Команда для разработки
CMD ["npm", "run", "start:dev"]
